name: SkriptInsightDocExtractionTool
version: @version@
main: io.github.skriptinsight.extractiontool.SkriptInsightDocExtractionTool
api-version: '1.13'
load: STARTUP
depend:
  - Skript
authors: [NickAc]
